var copyThot, titleHide, titleShow;

titleShow = function(type, num) {
  if (type !== "co" || "th") {
    $(".l" + type + num).css("visibility", "visible");
    $(".l" + type + num).collapse("show");
    switch (num) {
      case "1":
        $(".l" + type + "2, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "2, .l" + type + "3").collapse("show");
      case "2":
        $(".l" + type + "1, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "3").collapse("show");
      case "3":
        $(".l" + type + "1, .l" + type + "2").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "2").collapse("show");
    }
  } else {
    return $(".l" + type).collapse("show");
  }
};

titleHide = function(type, num) {
  if (type !== "co" || "th") {
    return $(".part-label").collapse("hide");
  } else {
    return $(".l" + type).collapse("hide");
  }
};

copyThot = function() {
  var essay;
  essay = ("\t" + ($("#th").val())) + ("\r\t" + ($("#ts1").val()) + " " + ($("#ex1").val()) + " " + ($("#cs1").val()) + "\r\t") + (($("#ts2").val()) + " " + ($("#ex2").val()) + " " + ($("#cs2").val()) + "\r\t") + (($("#ts3").val()) + " " + ($("#ex3").val()) + " " + ($("#cs3").val()) + "\r\t") + ("" + ($("#co").val()));
  return window.prompt("Copy to clipboard: Ctrl+C, Enter", essay);
};

// ---
// generated by coffee-script 1.9.2