var copyThot, titleHide, titleShow;

titleShow = function(type, num) {
  if (type !== "co" || "th") {
    $(".l" + type + num).css("visibility", "visible");
    $(".l" + type + num).collapse("show");
    switch (num) {
      case "1":
        $(".l" + type + "2, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "2, .l" + type + "3").collapse("show");
      case "2":
        $(".l" + type + "1, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "3").collapse("show");
      case "3":
        $(".l" + type + "1, .l" + type + "2").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "2").collapse("show");
    }
  } else {
    return $(".l" + type).collapse("show");
  }
};

titleHide = function(type, num) {
  if (type !== "co" || "th") {
    return $(".part-label").collapse("hide");
  } else {
    return $(".l" + type).collapse("hide");
  }
};

// ---
// generated by coffee-script 1.9.2