var titleHide, titleShow;

$(function() {
  return $('#preview-toggle').change(function() {
    var essay;
    if ($(this).prop("checked") === true) {
      essay = (($("#name").val()) + "<br>" + ($("#date-text").text()) + "<br>" + ($("#title").val()) + "<br><br>\t" + ($("#th").val())) + ("<br>\t" + ($("#ts1").val()) + " " + ($("#ex1").val()) + " " + ($("#cs1").val()) + "<br>\t") + (($("#ts2").val()) + " " + ($("#ex2").val()) + " " + ($("#cs2").val()) + "<br>\t") + (($("#ts3").val()) + " " + ($("#ex3").val()) + " " + ($("#cs3").val()) + "<br>\t") + ("" + ($("#co").val()));
      $("#preview").html(essay);
      $("#editor").hide(125);
      return $("#preview").show(125);
    } else {
      $("#preview").hide(125);
      return $("#editor").show(125);
    }
  });
});

titleShow = function(type, num) {
  if (type !== "co" || "th") {
    $(".l" + type + num).css("visibility", "visible");
    $(".l" + type + num).collapse("show");
    switch (num) {
      case "1":
        $(".l" + type + "2, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "2, .l" + type + "3").collapse("show");
      case "2":
        $(".l" + type + "1, .l" + type + "3").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "3").collapse("show");
      case "3":
        $(".l" + type + "1, .l" + type + "2").css("visibility", "hidden");
        return $(".l" + type + "1, .l" + type + "2").collapse("show");
    }
  } else {
    return $(".l" + type).collapse("show");
  }
};

titleHide = function(type, num) {
  if (type !== "co" || "th") {
    return $(".part-label").collapse("hide");
  } else {
    return $(".l" + type).collapse("hide");
  }
};

// ---
// generated by coffee-script 1.9.2